module.exports = {
  plugins: ['react'],
  rules: {
    'react/default-props-match-prop-types': 'off',
    'react/destructuring-assignment': 'off',
    'react/jsx-closing-bracket-location': 'off',
    'react/jsx-curly-spacing': 'off',
    'react/jsx-equals-spacing': 'off',
    'react/jsx-filename-extension': ['error', { extensions: ['.js'] }],
    'react/jsx-first-prop-new-line': 'off',
    'react/jsx-fragments': 'error',
    'react/jsx-indent-props': 'off',
    'react/jsx-indent': 'off',
    'react/jsx-sort-default-props': 'error',
    'react/jsx-sort-props': ['error', { reservedFirst: false }],
    'react/jsx-space-before-closing': 'off',
    'react/jsx-tag-spacing': 'off',
    'react/no-multi-comp': 'off',
    'react/sort-prop-types': ['error', { requiredFirst: true }],
  },
};
